name: Get Data from NRSC

on:
  schedule:
    - cron: '30 0,10-13,18 * * *' #Runs at 30 minutes past the hour, at 00:00, 10:00 through 13:00, and 18:59 UTC
  workflow_dispatch:

jobs:
  get-nrsc-data:
    runs-on: ubuntu-latest
    timeout-minutes: 19
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: spec-file.txt
          activate-environment: env
          auto-activate-base: false
      - name: Run script
        run: |
          python get_nrsc_data.py
      - name: Push new data
        run: |
          git add docs/*
          git commit -m "Data update : $(date)"
          git status
          git push
